//! tonic gRPC handler for reporting (Go `handler/grpc.go`
//! parity). Maps `proto/reporting/v1/reporting.proto` to/from the feature's
//! contract types and calls the usecase service — never domain
//! entities.
//!
//! The proto module is generated by `build.rs` into `OUT_DIR`. Package
//! `reporting.v1` (no `rust_package` override) makes `tonic::include_proto!`
//! emit a module named `reporting_v1`.

use std::sync::Arc;

use tonic::{Request, Response, Status};

use crate::features::reporting::contract::{SummaryRequest, SummaryResponse};
use crate::features::reporting::usecase::Service;
use crate::platform::errors::AppError;

/// 4 MiB cap on incoming + outgoing gRPC message bodies, matching the Go
/// template's `grpc.MaxRecvMsgSize(4*1024*1024)` / `MaxSendMsgSize(4*1024*1024)`.
const GRPC_MESSAGE_SIZE_LIMIT: usize = 4 * 1024 * 1024;

#[allow(clippy::double_must_use)] // generated `#[async_trait]` emits a must_use with no message
pub mod reporting_v1 {
    tonic::include_proto!("reporting.v1");
}

use reporting_v1::{
    CatalogStats as PbCatalogStats, MachineSales as PbMachineSales, MachineStats as PbMachineStats,
    SalesStats as PbSalesStats, SummaryRequest as PbSummaryRequest,
    SummaryResponse as PbSummaryResponse,
    reporting_service_server::{ReportingService, ReportingServiceServer},
};

/// tonic server implementation for the reporting feature. Generic over the
/// inbound port so tests inject a `MockService` and `di` wires `Arc<dyn Service>`.
pub struct GrpcServer<S: Service + ?Sized> {
    service: Arc<S>,
}

// Manual Clone impl: `Arc<S>` is `Clone` for any `S`, including `?Sized`.
impl<S: Service + ?Sized> Clone for GrpcServer<S> {
    fn clone(&self) -> Self {
        Self {
            service: self.service.clone(),
        }
    }
}

impl<S: Service + ?Sized> GrpcServer<S> {
    pub fn new(service: Arc<S>) -> Self {
        Self { service }
    }
}

#[tonic::async_trait]
impl<S: Service + ?Sized + 'static> ReportingService for GrpcServer<S> {
    async fn summary(
        &self,
        request: Request<PbSummaryRequest>,
    ) -> Result<Response<PbSummaryResponse>, Status> {
        let top = request.into_inner().top;
        let resp = self
            .service
            .summary(SummaryRequest { top: Some(top) })
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(contract_to_pb(&resp)))
    }
}

/// Build the tonic service wrapper with the message-size cap applied.
pub fn server<S>(srv: GrpcServer<S>) -> ReportingServiceServer<GrpcServer<S>>
where
    S: Service + ?Sized + 'static,
{
    ReportingServiceServer::new(srv)
        .max_decoding_message_size(GRPC_MESSAGE_SIZE_LIMIT)
        .max_encoding_message_size(GRPC_MESSAGE_SIZE_LIMIT)
}

fn contract_to_pb(resp: &SummaryResponse) -> PbSummaryResponse {
    PbSummaryResponse {
        catalog: Some(PbCatalogStats {
            product_count: resp.catalog.product_count,
            total_stock: resp.catalog.total_stock,
        }),
        machines: Some(PbMachineStats {
            machine_count: resp.machines.machine_count,
            total_coin_bank_cents: resp.machines.total_coin_bank_cents,
        }),
        sales: Some(PbSalesStats {
            purchase_count: resp.sales.purchase_count,
            revenue_cents: resp.sales.revenue_cents,
        }),
        top_machines: resp
            .top_machines
            .iter()
            .map(|m| PbMachineSales {
                machine_id: m.machine_id.clone(),
                label: m.label.clone(),
                purchase_count: m.purchase_count,
                revenue_cents: m.revenue_cents,
            })
            .collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::features::reporting::contract::{CatalogStats, MachineStats, SalesStats};
    use crate::features::reporting::usecase::MockService;

    fn sample_response() -> SummaryResponse {
        SummaryResponse {
            catalog: CatalogStats {
                product_count: 2,
                total_stock: 9,
            },
            machines: MachineStats {
                machine_count: 1,
                total_coin_bank_cents: 250,
            },
            sales: SalesStats {
                purchase_count: 3,
                revenue_cents: 300,
            },
            top_machines: vec![crate::features::reporting::contract::MachineSales {
                machine_id: "11111111-1111-1111-1111-111111111111".to_string(),
                label: "lobby".to_string(),
                purchase_count: 2,
                revenue_cents: 300,
            }],
        }
    }

    #[tokio::test]
    async fn summary_ok_maps_contract_to_proto() {
        let mut m = MockService::new();
        m.expect_summary()
            .withf(|req: &SummaryRequest| req.top == Some(3))
            .returning(|_| Ok(sample_response()));
        let srv = GrpcServer::new(Arc::new(m));

        let resp = srv
            .summary(Request::new(PbSummaryRequest { top: 3 }))
            .await
            .unwrap()
            .into_inner();
        assert_eq!(resp.catalog.unwrap().product_count, 2);
        assert_eq!(resp.machines.unwrap().total_coin_bank_cents, 250);
        assert_eq!(resp.sales.unwrap().revenue_cents, 300);
        assert_eq!(resp.top_machines.len(), 1);
        assert_eq!(resp.top_machines[0].label, "lobby");
    }

    #[tokio::test]
    async fn summary_maps_invalid_top_to_invalid_argument() {
        let mut m = MockService::new();
        m.expect_summary()
            .returning(|_| Err(crate::features::reporting::domain::Error::InvalidTopMachines));
        let srv = GrpcServer::new(Arc::new(m));

        let err = srv
            .summary(Request::new(PbSummaryRequest { top: 999 }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::InvalidArgument);
    }
}
