//! STUB FEATURE — delete src/features/example to start your project.
//!
//! tonic gRPC server for the example feature.
//!
//! Proto module is generated by `build.rs` into `OUT_DIR`. With package
//! `example.v1` and no `rust_package` override, `tonic::include_proto!` emits a
//! module named after the package name with dots replaced by underscores:
//! `example_v1`.

use std::sync::Arc;

use time::OffsetDateTime;
use tonic::{Request, Response, Status};
use uuid::Uuid;

use crate::features::example::domain::{Error, Service};
use crate::shared::errors::AppError;

pub mod example_v1 {
    tonic::include_proto!("example.v1");
}

use example_v1::{
    CreateItemRequest, GetItemRequest, Item, ListItemsRequest, ListItemsResponse,
    example_service_server::{ExampleService, ExampleServiceServer},
};

/// tonic server implementation of the example feature.
#[derive(Clone)]
pub struct GrpcServer<S: Service> {
    service: Arc<S>,
}

impl<S: Service + 'static> GrpcServer<S> {
    pub fn new(service: Arc<S>) -> Self {
        Self { service }
    }
}

#[tonic::async_trait]
impl<S: Service + 'static> ExampleService for GrpcServer<S> {
    async fn create_item(
        &self,
        request: Request<CreateItemRequest>,
    ) -> Result<Response<Item>, Status> {
        let req = request.into_inner();
        let item = self
            .service
            .create(req.name)
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(domain_to_pb(&item)))
    }

    async fn get_item(&self, request: Request<GetItemRequest>) -> Result<Response<Item>, Status> {
        let id = Uuid::parse_str(&request.into_inner().id)
            .map_err(|_| AppError::from(Error::InvalidId).to_grpc_status())?;
        let item = self
            .service
            .get(id)
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(domain_to_pb(&item)))
    }

    async fn list_items(
        &self,
        request: Request<ListItemsRequest>,
    ) -> Result<Response<ListItemsResponse>, Status> {
        let req = request.into_inner();
        let items = self
            .service
            .list(req.limit, req.offset)
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        let resp = ListItemsResponse {
            items: items.iter().map(domain_to_pb).collect(),
        };
        Ok(Response::new(resp))
    }
}

/// Build a tonic server suitable for `Server::add_service`.
pub fn server<S: Service + 'static>(srv: GrpcServer<S>) -> ExampleServiceServer<GrpcServer<S>> {
    ExampleServiceServer::new(srv)
}

fn domain_to_pb(item: &crate::features::example::domain::Item) -> Item {
    Item {
        id: item.id.to_string(),
        name: item.name.clone(),
        created_at: format_rfc3339(item.created_at),
        updated_at: format_rfc3339(item.updated_at),
    }
}

fn format_rfc3339(t: OffsetDateTime) -> String {
    use time::format_description::well_known::Rfc3339;
    t.format(&Rfc3339).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::features::example::domain::{Item, MockService};
    use mockall::predicate::*;

    fn sample() -> Item {
        let now = OffsetDateTime::now_utc();
        Item {
            id: Uuid::nil(),
            name: "alpha".to_string(),
            created_at: now,
            updated_at: now,
        }
    }

    #[tokio::test]
    async fn create_item_ok() {
        let mut m = MockService::new();
        m.expect_create().withf(|n| n == "alpha").returning(|n| {
            let mut s = sample();
            s.name = n.to_string();
            Ok(s)
        });
        let srv = GrpcServer::new(Arc::new(m));
        let resp = srv
            .create_item(Request::new(CreateItemRequest {
                name: "alpha".to_string(),
            }))
            .await
            .unwrap();
        assert_eq!(resp.into_inner().name, "alpha");
    }

    #[tokio::test]
    async fn create_item_maps_invalid_name_to_invalid_argument() {
        let mut m = MockService::new();
        m.expect_create().returning(|_| Err(Error::InvalidName));
        let srv = GrpcServer::new(Arc::new(m));
        let err = srv
            .create_item(Request::new(CreateItemRequest {
                name: "".to_string(),
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::InvalidArgument);
    }

    #[tokio::test]
    async fn get_item_ok() {
        let mut m = MockService::new();
        m.expect_get()
            .with(eq(Uuid::nil()))
            .returning(|_| Ok(sample()));
        let srv = GrpcServer::new(Arc::new(m));
        let resp = srv
            .get_item(Request::new(GetItemRequest {
                id: Uuid::nil().to_string(),
            }))
            .await
            .unwrap();
        assert_eq!(resp.into_inner().id, Uuid::nil().to_string());
    }

    #[tokio::test]
    async fn get_item_bad_uuid_maps_to_invalid_argument() {
        let m = MockService::new();
        let srv = GrpcServer::new(Arc::new(m));
        let err = srv
            .get_item(Request::new(GetItemRequest {
                id: "not-a-uuid".to_string(),
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::InvalidArgument);
    }

    #[tokio::test]
    async fn get_item_not_found_maps_to_not_found() {
        let mut m = MockService::new();
        m.expect_get().returning(|_| Err(Error::NotFound));
        let srv = GrpcServer::new(Arc::new(m));
        let err = srv
            .get_item(Request::new(GetItemRequest {
                id: Uuid::nil().to_string(),
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::NotFound);
    }

    #[tokio::test]
    async fn list_items_ok() {
        let mut m = MockService::new();
        m.expect_list()
            .returning(|_, _| Ok(vec![sample(), sample()]));
        let srv = GrpcServer::new(Arc::new(m));
        let resp = srv
            .list_items(Request::new(ListItemsRequest {
                limit: 10,
                offset: 0,
            }))
            .await
            .unwrap();
        assert_eq!(resp.into_inner().items.len(), 2);
    }
}
