// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTasksByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetTask(ctx context.Context, id pgtype.UUID) (Task, error)
	GetTaskByUserAndID(ctx context.Context, arg GetTaskByUserAndIDParams) (Task, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]Task, error)
	ListTasksByUserAndStatus(ctx context.Context, arg ListTasksByUserAndStatusParams) ([]Task, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchUsersByEmail(ctx context.Context, arg SearchUsersByEmailParams) ([]User, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
