apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: default

resources:
  - ../base

commonLabels:
  app.kubernetes.io/instance: development

replicas:
  - name: zercle-rust-template
    count: 1
