apiVersion: v1
kind: Service
metadata:
  name: zercle-rust-template
spec:
  selector:
    app.kubernetes.io/name: zercle-rust-template
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
