//! tonic gRPC driving adapter for sales (Go `adapter/in/grpc/server.go`
//! parity, port-spec §5.3a). Maps `proto/sales/v1/sales.proto` payloads
//! to/from the feature's contract types and calls `application::Service` —
//! never domain entities.
//!
//! Proto module generated by `build.rs` into `OUT_DIR`. With package
//! `sales.v1` and no `rust_package` override, `tonic::include_proto!` emits a
//! module named after the package with dots replaced by underscores:
//! `sales_v1`.
//!
//! May reference only the application port and contract
//! (`tests/architecture.rs`: driving-adapters-ignore-ports-and-driven-adapters).

use std::sync::Arc;

use tonic::{Request, Response, Status};

use crate::features::sales::application::Service;
use crate::features::sales::contract::{PurchaseRequest, PurchaseResponse};
use crate::platform::errors::AppError;

/// 4 MiB cap on incoming + outgoing gRPC message bodies (Go
/// `grpc.MaxRecvMsgSize(4*1024*1024)` / `MaxSendMsgSize(4*1024*1024)`); owned
/// by the feature to protect its payloads.
const GRPC_MESSAGE_SIZE_LIMIT: usize = 4 * 1024 * 1024;

pub mod sales_v1 {
    // tonic's generated server trait boxes its futures and the `async_trait`
    // expansion adds a message-less `#[must_use]`, which trips
    // `clippy::double_must_use` on generated code we do not own.
    #![allow(clippy::double_must_use)]

    tonic::include_proto!("sales.v1");
}

use sales_v1::{
    PurchaseRequest as PbPurchaseRequest, PurchaseResponse as PbPurchaseResponse,
    sales_service_server::{SalesService, SalesServiceServer},
};

/// tonic server implementation for the sales feature. Generic over the inbound
/// port so tests inject a `MockService` and `di` wires `Arc<dyn Service>`.
pub struct GrpcServer<S: Service + ?Sized> {
    service: Arc<S>,
}

// Manual Clone impl: `Arc<S>` is `Clone` for any `S`, including `?Sized`.
impl<S: Service + ?Sized> Clone for GrpcServer<S> {
    fn clone(&self) -> Self {
        Self {
            service: self.service.clone(),
        }
    }
}

impl<S: Service + ?Sized + 'static> GrpcServer<S> {
    pub fn new(service: Arc<S>) -> Self {
        Self { service }
    }
}

#[tonic::async_trait]
impl<S: Service + ?Sized + 'static> SalesService for GrpcServer<S> {
    async fn purchase(
        &self,
        request: Request<PbPurchaseRequest>,
    ) -> Result<Response<PbPurchaseResponse>, Status> {
        let req = request.into_inner();
        let resp = self
            .service
            .purchase(PurchaseRequest {
                machine_id: req.machine_id,
                product_id: req.product_id,
                coins: req.coins,
            })
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(contract_to_pb(resp)))
    }
}

/// Build the tonic service with the feature's message-size caps applied.
pub fn server<S>(srv: GrpcServer<S>) -> SalesServiceServer<GrpcServer<S>>
where
    S: Service + ?Sized + 'static,
{
    SalesServiceServer::new(srv)
        .max_decoding_message_size(GRPC_MESSAGE_SIZE_LIMIT)
        .max_encoding_message_size(GRPC_MESSAGE_SIZE_LIMIT)
}

fn contract_to_pb(resp: PurchaseResponse) -> PbPurchaseResponse {
    PbPurchaseResponse {
        id: resp.id,
        machine_id: resp.machine_id,
        product_id: resp.product_id,
        price_cents: resp.price_cents,
        total_inserted_cents: resp.total_inserted_cents,
        change_cents: resp.change_cents,
        change_coins: resp.change_coins,
        purchased_at: resp.purchased_at,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::features::sales::application::MockService;
    use crate::features::sales::domain::Error as DomainError;

    fn sample() -> PurchaseResponse {
        PurchaseResponse {
            id: "id".to_string(),
            machine_id: "m".to_string(),
            product_id: "p".to_string(),
            price_cents: 25,
            total_inserted_cents: 100,
            change_cents: 75,
            change_coins: vec![50, 25],
            purchased_at: "1970-01-01T00:00:00Z".to_string(),
        }
    }

    #[tokio::test]
    async fn purchase_ok() {
        let mut m = MockService::new();
        m.expect_purchase()
            .withf(|req| req.machine_id == "m" && req.coins == vec![100])
            .returning(|_| Ok(sample()));
        let srv = GrpcServer::new(Arc::new(m));
        let resp = srv
            .purchase(Request::new(PbPurchaseRequest {
                machine_id: "m".to_string(),
                product_id: "p".to_string(),
                coins: vec![100],
            }))
            .await
            .unwrap()
            .into_inner();
        assert_eq!(resp.change_cents, 75);
        assert_eq!(resp.change_coins, vec![50, 25]);
    }

    #[tokio::test]
    async fn purchase_maps_domain_errors_to_status_codes() {
        // `domain::Error` is not `Clone` (its `Internal` cause is an `anyhow::Error`),
        // so carry the unit-variant constructors as `fn() -> Error` factories.
        let cases: [(fn() -> DomainError, tonic::Code); 4] = [
            (|| DomainError::MachineNotFound, tonic::Code::NotFound),
            (|| DomainError::OutOfStock, tonic::Code::AlreadyExists),
            (
                || DomainError::UnsupportedCoin,
                tonic::Code::InvalidArgument,
            ),
            (
                || DomainError::InsufficientPayment,
                tonic::Code::InvalidArgument,
            ),
        ];
        for (make, expected) in cases {
            let mut m = MockService::new();
            m.expect_purchase().returning(move |_| Err(make()));
            let srv = GrpcServer::new(Arc::new(m));
            let err = srv
                .purchase(Request::new(PbPurchaseRequest {
                    machine_id: "m".to_string(),
                    product_id: "p".to_string(),
                    coins: vec![25],
                }))
                .await
                .unwrap_err();
            assert_eq!(err.code(), expected);
        }
    }
}
