//! STUB FEATURE — delete src/features/example to start your project.
//!
//! tonic gRPC driving adapter for the example feature (Go
//! `adapter/in/grpc/server.go` parity). Maps proto payloads to/from the
//! feature's contract types and calls the application's inbound port — never
//! domain entities.
//!
//! Proto module is generated by `build.rs` into `OUT_DIR`. With package
//! `example.v1` and no `rust_package` override, `tonic::include_proto!` emits a
//! module named after the package name with dots replaced by underscores:
//! `example_v1`.

use std::sync::Arc;

use tonic::{Request, Response, Status};

use crate::features::example::application::Service;
use crate::features::example::contract::{CreateItemRequest, ItemResponse, ListItemsRequest};
use crate::platform::errors::AppError;

/// 4 MiB cap on incoming + outgoing gRPC message bodies. Matches Go's
/// `grpc.MaxRecvMsgSize(4*1024*1024)` / `MaxSendMsgSize(4*1024*1024)`; owned
/// by the feature because it protects this service's payloads.
const GRPC_MESSAGE_SIZE_LIMIT: usize = 4 * 1024 * 1024;

pub mod example_v1 {
    tonic::include_proto!("example.v1");
}

use example_v1::{
    CreateItemRequest as PbCreateItemRequest, ListItemsRequest as PbListItemsRequest,
};
use example_v1::{
    GetItemRequest, Item as PbItem, ListItemsResponse as PbListItemsResponse,
    example_service_server::{ExampleService, ExampleServiceServer},
};

/// tonic server implementation of the example feature. Generic over the
/// inbound port so tests inject a `MockService` and the `di` wires
/// `Arc<dyn Service>`.
pub struct GrpcServer<S: Service + ?Sized> {
    service: Arc<S>,
}

// Manual Clone impl: `Arc<S>` is `Clone` for any `S`, including `?Sized`.
impl<S: Service + ?Sized> Clone for GrpcServer<S> {
    fn clone(&self) -> Self {
        Self {
            service: self.service.clone(),
        }
    }
}

impl<S: Service + ?Sized + 'static> GrpcServer<S> {
    pub fn new(service: Arc<S>) -> Self {
        Self { service }
    }
}

#[tonic::async_trait]
impl<S: Service + ?Sized + 'static> ExampleService for GrpcServer<S> {
    async fn create_item(
        &self,
        request: Request<PbCreateItemRequest>,
    ) -> Result<Response<PbItem>, Status> {
        let req = request.into_inner();
        let resp = self
            .service
            .create(CreateItemRequest { name: req.name })
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(contract_to_pb(&resp)))
    }

    async fn get_item(&self, request: Request<GetItemRequest>) -> Result<Response<PbItem>, Status> {
        let id = request.into_inner().id;
        let resp = self
            .service
            .get(id)
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(contract_to_pb(&resp)))
    }

    async fn list_items(
        &self,
        request: Request<PbListItemsRequest>,
    ) -> Result<Response<PbListItemsResponse>, Status> {
        let req = request.into_inner();
        let resp = self
            .service
            .list(ListItemsRequest {
                limit: Some(req.limit),
                offset: Some(req.offset),
            })
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(PbListItemsResponse {
            items: resp.items.iter().map(contract_to_pb).collect(),
        }))
    }
}

/// Build a tonic service suitable for `Server::add_service`, with the message
/// size limits applied.
pub fn server<S: Service + ?Sized + 'static>(
    srv: GrpcServer<S>,
) -> ExampleServiceServer<GrpcServer<S>> {
    ExampleServiceServer::new(srv)
        .max_decoding_message_size(GRPC_MESSAGE_SIZE_LIMIT)
        .max_encoding_message_size(GRPC_MESSAGE_SIZE_LIMIT)
}

fn contract_to_pb(resp: &ItemResponse) -> PbItem {
    PbItem {
        id: resp.id.clone(),
        name: resp.name.clone(),
        created_at: resp.created_at.clone(),
        updated_at: resp.updated_at.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::features::example::application::MockService;
    use mockall::predicate::*;

    fn sample(id: &str, name: &str) -> ItemResponse {
        ItemResponse {
            id: id.to_string(),
            name: name.to_string(),
            created_at: "1970-01-01T00:00:00Z".to_string(),
            updated_at: "1970-01-01T00:00:00Z".to_string(),
        }
    }

    #[tokio::test]
    async fn create_item_ok() {
        let mut m = MockService::new();
        m.expect_create()
            .withf(|req: &CreateItemRequest| req.name == "alpha")
            .returning(|req| Ok(sample("some-id", &req.name)));
        let srv = GrpcServer::new(Arc::new(m));
        let resp = srv
            .create_item(Request::new(PbCreateItemRequest {
                name: "alpha".to_string(),
            }))
            .await
            .unwrap();
        assert_eq!(resp.into_inner().name, "alpha");
    }

    #[tokio::test]
    async fn create_item_maps_invalid_name_to_invalid_argument() {
        let mut m = MockService::new();
        m.expect_create()
            .returning(|_| Err(crate::features::example::domain::Error::InvalidName));
        let srv = GrpcServer::new(Arc::new(m));
        let err = srv
            .create_item(Request::new(PbCreateItemRequest {
                name: "".to_string(),
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::InvalidArgument);
    }

    #[tokio::test]
    async fn get_item_ok() {
        let mut m = MockService::new();
        m.expect_get()
            .withf(|id| id == "00000000-0000-0000-0000-000000000000")
            .returning(|id| Ok(sample(&id, "alpha")));
        let srv = GrpcServer::new(Arc::new(m));
        let resp = srv
            .get_item(Request::new(GetItemRequest {
                id: uuid::Uuid::nil().to_string(),
            }))
            .await
            .unwrap();
        assert_eq!(resp.into_inner().id, uuid::Uuid::nil().to_string());
    }

    #[tokio::test]
    async fn get_item_bad_uuid_maps_to_invalid_argument() {
        let mut m = MockService::new();
        m.expect_get()
            .returning(|_| Err(crate::features::example::domain::Error::InvalidId));
        let srv = GrpcServer::new(Arc::new(m));
        let err = srv
            .get_item(Request::new(GetItemRequest {
                id: "not-a-uuid".to_string(),
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::InvalidArgument);
    }

    #[tokio::test]
    async fn get_item_not_found_maps_to_not_found() {
        let mut m = MockService::new();
        m.expect_get()
            .returning(|_| Err(crate::features::example::domain::Error::NotFound));
        let srv = GrpcServer::new(Arc::new(m));
        let err = srv
            .get_item(Request::new(GetItemRequest {
                id: uuid::Uuid::nil().to_string(),
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::NotFound);
    }

    #[tokio::test]
    async fn list_items_ok() {
        let mut m = MockService::new();
        m.expect_list()
            .withf(|req: &ListItemsRequest| req.limit == Some(10) && req.offset == Some(0))
            .returning(|_| {
                Ok(crate::features::example::contract::ListItemsResponse {
                    items: vec![sample("a", "one"), sample("b", "two")],
                })
            });
        let srv = GrpcServer::new(Arc::new(m));
        let resp = srv
            .list_items(Request::new(PbListItemsRequest {
                limit: 10,
                offset: 0,
            }))
            .await
            .unwrap();
        assert_eq!(resp.into_inner().items.len(), 2);
    }
}
