//! Stable machine-readable error codes carried on the wire (the HTTP JSON
//! `error` field). Mirrors Go `pkg/api/errcodes` (port-spec §3).
//!
//! This module is the single source of the code strings. The published facade
//! [`crate::api::errcodes`] re-exports them (plus the Go-parity CamelCase
//! aliases) for external consumers, and [`crate::platform::errors::AppError`]
//! sources its `code()` values here — so the literals are defined once.

pub const NOT_FOUND: &str = "NOT_FOUND";
pub const INVALID_INPUT: &str = "INVALID_INPUT";
pub const UNAUTHORIZED: &str = "UNAUTHORIZED";
pub const FORBIDDEN: &str = "FORBIDDEN";
pub const CONFLICT: &str = "CONFLICT";
pub const CANCELED: &str = "CANCELED";
pub const DEADLINE_EXCEEDED: &str = "DEADLINE_EXCEEDED";
pub const INTERNAL: &str = "INTERNAL";

/// Codes for errors generated by the HTTP framework itself rather than by
/// application logic (Go `errcodes.MethodNotAllowed` / `PayloadTooLarge`).
pub const METHOD_NOT_ALLOWED: &str = "METHOD_NOT_ALLOWED";
pub const PAYLOAD_TOO_LARGE: &str = "PAYLOAD_TOO_LARGE";
