//! tonic gRPC handler for catalog (Go `handler/grpc.go`
//! parity, port-spec §5.1a). Maps proto payloads to/from the feature's
//! contract types and calls the usecase service — never mapping
//! from domain entities.
//!
//! The proto module is generated by `build.rs` into `OUT_DIR`; with package
//! `catalog.v1` and no `rust_package` override, `tonic::include_proto!` emits
//! a module named after the package with dots replaced by underscores:
//! `catalog_v1`.

use std::sync::Arc;

use tonic::{Request, Response, Status};

use crate::features::catalog::contract::{
    CreateProductRequest, ListProductsRequest, ProductResponse,
};
use crate::features::catalog::usecase::Service;
use crate::platform::errors::AppError;

/// 4 MiB cap on incoming + outgoing gRPC message bodies (Go
/// `grpc.MaxRecvMsgSize`/`MaxSendMsgSize` parity; owned by the feature to
/// protect the service's payloads).
const GRPC_MESSAGE_SIZE_LIMIT: usize = 4 * 1024 * 1024;

// The generated `CatalogService` trait carries `#[async_trait]`, whose boxed
// futures trip `clippy::double_must_use`; the attribute lives in `OUT_DIR` and
// cannot be fixed at source, so allow it for the whole generated module.
#[allow(clippy::double_must_use)]
pub mod catalog_v1 {
    tonic::include_proto!("catalog.v1");
}

use catalog_v1::{
    CreateProductRequest as PbCreateProductRequest, GetProductRequest,
    ListProductsRequest as PbListProductsRequest, ListProductsResponse as PbListProductsResponse,
    Product as PbProduct,
    catalog_service_server::{CatalogService, CatalogServiceServer},
};

/// tonic server implementation for the catalog feature. Generic over the
/// inbound port so tests inject a `MockService` and `di` wires
/// `Arc<dyn Service>`.
pub struct GrpcServer<S: Service + ?Sized> {
    service: Arc<S>,
}

// Manual `Clone` impl: `Arc<S>` is `Clone` for any `S`, including `?Sized`.
impl<S: Service + ?Sized> Clone for GrpcServer<S> {
    fn clone(&self) -> Self {
        Self {
            service: self.service.clone(),
        }
    }
}

impl<S: Service + ?Sized> GrpcServer<S> {
    pub fn new(service: Arc<S>) -> Self {
        Self { service }
    }
}

#[tonic::async_trait]
impl<S: Service + ?Sized + 'static> CatalogService for GrpcServer<S> {
    async fn create_product(
        &self,
        request: Request<PbCreateProductRequest>,
    ) -> Result<Response<PbProduct>, Status> {
        let req = request.into_inner();
        let response = self
            .service
            .create(CreateProductRequest {
                name: req.name,
                price_cents: req.price_cents,
                stock: req.stock,
            })
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(contract_to_pb(&response)))
    }

    async fn get_product(
        &self,
        request: Request<GetProductRequest>,
    ) -> Result<Response<PbProduct>, Status> {
        let id = request.into_inner().id;
        let response = self
            .service
            .get(id)
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(contract_to_pb(&response)))
    }

    async fn list_products(
        &self,
        request: Request<PbListProductsRequest>,
    ) -> Result<Response<PbListProductsResponse>, Status> {
        let req = request.into_inner();
        let response = self
            .service
            .list(ListProductsRequest {
                limit: Some(req.limit),
                offset: Some(req.offset),
            })
            .await
            .map_err(|e| AppError::from(e).to_grpc_status())?;
        Ok(Response::new(PbListProductsResponse {
            products: response.products.iter().map(contract_to_pb).collect(),
        }))
    }
}

/// Build the tonic service for `srv` with the feature's message-size caps.
pub fn server<S: Service + ?Sized + 'static>(
    srv: GrpcServer<S>,
) -> CatalogServiceServer<GrpcServer<S>> {
    CatalogServiceServer::new(srv)
        .max_decoding_message_size(GRPC_MESSAGE_SIZE_LIMIT)
        .max_encoding_message_size(GRPC_MESSAGE_SIZE_LIMIT)
}

fn contract_to_pb(resp: &ProductResponse) -> PbProduct {
    PbProduct {
        id: resp.id.clone(),
        name: resp.name.clone(),
        price_cents: resp.price_cents,
        stock: resp.stock,
        created_at: resp.created_at.clone(),
        updated_at: resp.updated_at.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::features::catalog::contract::ListProductsResponse;
    use crate::features::catalog::usecase::MockService;

    fn sample(id: &str, name: &str) -> ProductResponse {
        ProductResponse {
            id: id.to_string(),
            name: name.to_string(),
            price_cents: 150,
            stock: 2,
            created_at: "1970-01-01T00:00:00Z".to_string(),
            updated_at: "1970-01-01T00:00:00Z".to_string(),
        }
    }

    #[tokio::test]
    async fn create_product_ok() {
        let mut m = MockService::new();
        m.expect_create()
            .withf(|req: &CreateProductRequest| req.name == "alpha")
            .returning(|req| Ok(sample("some-id", &req.name)));
        let srv = GrpcServer::new(Arc::new(m));

        let resp = srv
            .create_product(Request::new(PbCreateProductRequest {
                name: "alpha".to_string(),
                price_cents: 150,
                stock: 2,
            }))
            .await
            .unwrap();
        assert_eq!(resp.into_inner().name, "alpha");
    }

    #[tokio::test]
    async fn create_product_maps_invalid_price_to_invalid_argument() {
        let mut m = MockService::new();
        m.expect_create()
            .returning(|_| Err(crate::features::catalog::domain::Error::InvalidPrice));
        let srv = GrpcServer::new(Arc::new(m));

        let err = srv
            .create_product(Request::new(PbCreateProductRequest {
                name: "alpha".to_string(),
                price_cents: 0,
                stock: 0,
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::InvalidArgument);
    }

    #[tokio::test]
    async fn get_product_maps_not_found_to_not_found() {
        let mut m = MockService::new();
        m.expect_get()
            .returning(|_| Err(crate::features::catalog::domain::Error::ProductNotFound));
        let srv = GrpcServer::new(Arc::new(m));

        let err = srv
            .get_product(Request::new(GetProductRequest {
                id: "00000000-0000-0000-0000-000000000000".to_string(),
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::NotFound);
    }

    #[tokio::test]
    async fn list_products_maps_fields() {
        let mut m = MockService::new();
        m.expect_list()
            .withf(|req: &ListProductsRequest| req.limit == Some(10) && req.offset == Some(0))
            .returning(|_| {
                Ok(ListProductsResponse {
                    products: vec![sample("id-1", "a"), sample("id-2", "b")],
                })
            });
        let srv = GrpcServer::new(Arc::new(m));

        let resp = srv
            .list_products(Request::new(PbListProductsRequest {
                limit: 10,
                offset: 0,
            }))
            .await
            .unwrap();
        assert_eq!(resp.into_inner().products.len(), 2);
    }
}
